### ISSUE TITLE
Feature requests + bug

### ISSUE THREAD

**Issue by richwiss** [acl2017/acl2017.github.io#35]
---

## Environment information

- **Platform:** 
- Mac Sierra 10.12.4
- Chrome 57.0.2987.133 (64-bit)

---

## Feature Request

Feature request: When I'm trying to decide between papers at a specific time, it's a bit tedious to have to open each parallel session. Maybe when I select, e.g. Machine Translation I, it should also open the corresponding Parsing and Named Entity Recognition parallel sessions so I can easily browse.

Feature request: Warning folks is fine, but sometimes I'm undecided until the last minute about which talk to attend and it would be good to allow conflicting papers in the schedule. That said... (see bug)

## Bug

Bug: Some time slots don't align properly in the schedule and the scheduler doesn't catch this. For example, I can select the paper in Word Embeddings I from 4:40-5:00 and still select the paper in Anaphora Resolution from 4:50-5:00 despite clearly being unable to fully attend both.

**Comment by desilinguist** [comment]
Thanks so much for testing this @richwiss and reporting the bug! That definitely requires a fix.

As for you feature suggestions, I like the idea of automatically expanding all parallel sessions but I am a little reluctant because though the sessions appear adjacent to each other in a desktop browser, they are sequential in a mobile browser and automatically expanding those might be a little disorienting for the user. 

I do see your point about possibly allowing conflicts in the schedule too. It would make the code a little more complicated though so I'd like to see if this is a really popular feature request.

**Comment by desilinguist** [comment]
Hi @richwiss

Conflicts are now called in the schedule. It would be nice if you can try testing it again. Thanks!
