### ISSUE TITLE
Paper abstracts?

### ISSUE THREAD

**Issue by nschneid** [acl2017/acl2017.github.io#40]
If there is a time slot where I can't decide between 2 papers, I usually go and read the abstracts. It might be nice to include the abstracts (hidden by default) or else a link to open the abstract in a new window.

**Comment by desilinguist** [comment]
Ah, that's a nice idea. I will try to get those from the program chairs and incorporate them into the program page.

**Comment by desilinguist** [comment]
I am not really sure where to incorporate the abstracts since due to 5 parallel sessions, things are already quite constrained in terms of space. The click event on a paper is already bound to the function of selecting it for inclusion in the PDF so I don't want to overload it. I think the easiest solution is to simply provide a link to the [page](https://chairs-blog.acl2017.org/2017/06/04/preliminary-paper-details/) on the ACL chairs blog that has all of the abstracts right at the top of the program page so folks can open it in a new tab and look for the abstract themselves.
