### ISSUE TITLE
Remember selections across sessions

### ISSUE THREAD

**Issue by danielhers** [acl2017/acl2017.github.io#43]
User log-in may be an overkill, but cookies could be used to remember the selections in the same device.

**Comment by desilinguist** [comment]
User log-in can't be done anyway because the whole website is based on GitHub static pages so there is no database available for user management. 

As for the cookie option, I am not really sure how necessary this is given that I usually keep the tab open until I am done with it if I don't finish it off in one go. Let's see if other folks request this too. 

Thanks!

**Comment by desilinguist** [comment]
No one else requested this so I will close this for now.
